name: build dra test-driver image with cdi

on:
  workflow_dispatch:
    inputs:
      image: # optional
        type: string
        description: 'Image name'
        required: false
        default: 'test-driver-cdi'
      tag:
        type: string
        description: 'Tag to build'
        required: false
        default: 'latest'
  push:
    branches:
      #      - master
#      - release-1.26
  pull_request:
    branches:
      - master

# permissions:
#   contents: read

jobs:
  docker:
    name: build dra test-driver image with cdi
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        docker_version: ["20.10"]
        docker_channel: ["stable"]
    env:
      JOB_NAME: "docker-${{ matrix.docker_version }}-${{ matrix.docker_channel }}"
      TEST_DRIVER_IMAGE: node-cdi
      TEST_DRIVER_TAG: latest
    #      TEST_DRIVER_IMAGE: ${{ github.event.inputs.image }}
    #      TEST_DRIVER_TAG: ${{ github.event.inputs.tag }}
    #       IP_FAMILY: ${{ matrix.ipFamily }}
    steps:
#      - name: checkout
#        uses: actions/checkout@v3
#        with:
#          ref: 'release-1.26'
      - name: Clone kubernetes repo
        run: |
          cd /home/runner/work
          git clone https://github.com/kubernetes/kubernetes
          pwd
          uname -a
          cd kubernetes
          ls
          git switch release-1.26
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      - name: Setup Go Env
#        uses: actions/setup-go@v3
#        with:
#          go-version: '>=1.19.3'
#          cache: true
#          cache-dependency-path: go.sum
#      - name: Check Go Env
#        run: go version
      - name: Install Kind
        run: |
          curl -Lo ./kind "https://kind.sigs.k8s.io/dl/v0.17.0/kind-$(uname)-amd64"
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
      - name: Build kind-dra-node-image
        run: |
          cd kubernetes
          chmod +x test/e2e/dra/kind-build-image.sh
          test/e2e/dra/kind-build-image.sh dra/node:latest
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: push
        run: |
          docker tag dra/node:latest ghcr.io/${{ env.OWNER_LC }}/${{ env.TEST_DRIVER_IMAGE }}-controller:${{ env.TEST_DRIVER_TAG }}
          docker push ghcr.io/${{ env.OWNER_LC }}/${{ env.TEST_DRIVER_IMAGE }}-controller:${{ env.TEST_DRIVER_TAG }}